import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-slate-100 w-screen h-screen overflow-none flex flex-col  ${inter.className}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
